# Generated by Django 5.1.3 on 2024-12-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_data',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='blog',
            name='count_view',
            field=models.IntegerField(null=True, verbose_name='Количество просмотров'),
        ),
    ]
