# Generated by Django 5.1.3 on 2024-12-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_data_blog_data_alter_blog_count_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
